//*****************************************************************************
// ReflectCatalog.gen.h — GENERATED by Tools/reflect_codegen.py. DO NOT EDIT.
//*****************************************************************************
#pragma once

#include <cstddef>

namespace Catty
{
namespace ReflectCatalog
{

enum class EReflectMemberKind : unsigned
{
	Property = 0,
	Function = 1,
};

struct FReflectMemberInfo
{
	const char* Name;
	EReflectMemberKind Kind;
};

struct FReflectTypeInfo
{
	const char* TypeName;
	const char* SourceFile;
	int SourceLine;
	const FReflectMemberInfo* Members;
	std::size_t MemberCount;
};

inline constexpr FReflectMemberInfo GMembers_Catty__ReflectPrivate__FReflectSmoke[] =
{
	{ "X", EReflectMemberKind::Property },
	{ "Y", EReflectMemberKind::Property },
	{ "Scale", EReflectMemberKind::Function },
};

inline constexpr FReflectTypeInfo GTypes[] =
{
	{
		"Catty::ReflectPrivate::FReflectSmoke",
		"Catty/Source/Private/Core/Reflect.cpp",
		23,
		GMembers_Catty__ReflectPrivate__FReflectSmoke,
		3
	},
};

inline constexpr std::size_t GTypeCount = 1;

} // namespace ReflectCatalog
} // namespace Catty
